#!/usr/bin/env bash
# crawler-lists-gate.sh - gate on the completeness of the published kernel-crawler lists.
#
# Purpose:
#   dbg-go `configs generate --auto` rebuilds the Drivers Build Grid configs from the kernel lists
#   published by kernel-crawler. A list can be silently partial (a whole distro missing, or far
#   fewer kernels than before) while the crawler run stays green; regenerating from it would drop
#   drivers. This script compares, per distro and arch, the kernel count in the published list
#   with the number of config files in a reference driver-version directory of test-infra
#   (driverkit/config/<driver-version>/<arch>/, read through the git trees API - never the PR
#   files API, which caps at 3000 files).
#   Per distro:  OK|LOW|MISSING <arch> <distro> list=<n> configs=<m> min=<threshold>
#   Distros present in the list but without configs (not generated by dbg-go) are printed as SKIP.
#   Final token: CRAWLER_LISTS_OK or CRAWLER_LISTS_BLOCK (always the last line).
#
# Usage:
#   crawler-lists-gate.sh --arch <x86_64|aarch64> [--arch ...] --driver-version <X.Y.Z+driver>
#                         [--min-ratio 0.9] [--distro NAME ...] [--lists-base-url URL]
#                         [--config-repo owner/repo] [--config-ref REF] [--config-path PATH]
#                         [--workdir </abs/dir>] [--timeout SEC]
#
# Exit codes:
#   0  every distro with configs is OK
#   1  at least one distro is LOW or MISSING (block the regeneration)
#   2  usage error
#   4  a download or API error prevented the evaluation
#
# Read-only (curl GET, gh api GET).
#
# Sources of the expectations:
#   falcosecurity/dbg-go pkg/root/distro.go         supported distros = the ones with configs in test-infra
#   falcosecurity/dbg-go pkg/root/constants.go      config/output naming <driver>_<target>_<kernelrelease>_<kernelversion>
#   falcosecurity/test-infra driverkit/config/<driver-version>/<arch>/<target>_<kernelrelease>_<kernelversion>.yaml
#   kernel-crawler published lists: https://falcosecurity.github.io/kernel-crawler/<arch>/list.json
#     (object keyed by distro; ubuntu entries carry flavour targets ubuntu-<flavour>, so config targets
#      "<distro>-<flavour>" are folded into the list key "<distro>")
#
# Example:
#   crawler-lists-gate.sh --arch x86_64 --arch aarch64 --driver-version 11.0.0+driver --min-ratio 0.9
set -euo pipefail

# ---- project defaults (overridable by flags) ---------------------------------------------------
DEFAULT_LISTS_BASE_URL="https://falcosecurity.github.io/kernel-crawler"   # kernel-crawler GitHub Pages (Update Kernels workflow)
DEFAULT_CONFIG_REPO="falcosecurity/test-infra"                            # DBG configs repository
DEFAULT_CONFIG_REF="master"
DEFAULT_CONFIG_PATH="driverkit/config"                                    # dbg-go pkg/root/constants.go configPathFmt
DEFAULT_MIN_RATIO="0.9"
DEFAULT_TIMEOUT=60

usage() {
  cat <<'EOF'
Usage: crawler-lists-gate.sh --arch <x86_64|aarch64> [--arch ...] --driver-version <X.Y.Z+driver>
                             [--min-ratio 0.9] [--distro NAME ...] [--lists-base-url URL]
                             [--config-repo owner/repo] [--config-ref REF] [--config-path PATH]
                             [--workdir </abs/dir>] [--timeout SEC]

Compare per-distro kernel counts of the published kernel-crawler lists with the reference DBG configs.
  --arch            repeatable, at least one of x86_64, aarch64
  --driver-version  reference config directory, e.g. 11.0.0+driver
  --min-ratio       list/configs ratio below which a distro is LOW (default 0.9)
  --distro          repeatable; restrict the evaluation to these distros (default: every distro with configs)
  --lists-base-url  default https://falcosecurity.github.io/kernel-crawler
  --config-repo     default falcosecurity/test-infra
  --config-ref      default master
  --config-path     default driverkit/config
  --workdir         absolute directory for downloads (default: a fresh mktemp directory)
  --timeout         per-request timeout in seconds (default 60)

Output: OK|LOW|MISSING|SKIP|ERROR lines, then CRAWLER_LISTS_OK or CRAWLER_LISTS_BLOCK as the last line.
Exit codes: 0 all OK; 1 LOW or MISSING; 2 usage; 4 download/API error.
Example: crawler-lists-gate.sh --arch x86_64 --arch aarch64 --driver-version 11.0.0+driver
EOF
}

die_usage() { printf 'error: %s\n\n' "$1" >&2; usage >&2; exit 2; }

ARCHES=() DISTROS=() DRIVER_VERSION="" MIN_RATIO="$DEFAULT_MIN_RATIO" LISTS_BASE_URL="$DEFAULT_LISTS_BASE_URL"
CONFIG_REPO="$DEFAULT_CONFIG_REPO" CONFIG_REF="$DEFAULT_CONFIG_REF" CONFIG_PATH="$DEFAULT_CONFIG_PATH" WORKDIR="" TIMEOUT="$DEFAULT_TIMEOUT"
while [ $# -gt 0 ]; do
  case "$1" in
    --help|-h) usage; exit 0 ;;
    --arch) [ $# -ge 2 ] || die_usage "--arch needs a value"; ARCHES+=("$2"); shift 2 ;;
    --driver-version) [ $# -ge 2 ] || die_usage "--driver-version needs a value"; DRIVER_VERSION="$2"; shift 2 ;;
    --min-ratio) [ $# -ge 2 ] || die_usage "--min-ratio needs a value"; MIN_RATIO="$2"; shift 2 ;;
    --distro) [ $# -ge 2 ] || die_usage "--distro needs a value"; DISTROS+=("$2"); shift 2 ;;
    --lists-base-url) [ $# -ge 2 ] || die_usage "--lists-base-url needs a value"; LISTS_BASE_URL="${2%/}"; shift 2 ;;
    --config-repo) [ $# -ge 2 ] || die_usage "--config-repo needs a value"; CONFIG_REPO="$2"; shift 2 ;;
    --config-ref) [ $# -ge 2 ] || die_usage "--config-ref needs a value"; CONFIG_REF="$2"; shift 2 ;;
    --config-path) [ $# -ge 2 ] || die_usage "--config-path needs a value"; CONFIG_PATH="${2#/}"; CONFIG_PATH="${CONFIG_PATH%/}"; shift 2 ;;
    --workdir) [ $# -ge 2 ] || die_usage "--workdir needs a value"; WORKDIR="$2"; shift 2 ;;
    --timeout) [ $# -ge 2 ] || die_usage "--timeout needs a value"; TIMEOUT="$2"; shift 2 ;;
    *) die_usage "unknown argument: $1" ;;
  esac
done
[ "${#ARCHES[@]}" -gt 0 ] || die_usage "at least one --arch is required"
for a in "${ARCHES[@]}"; do
  case "$a" in x86_64|aarch64) ;; *) die_usage "--arch must be x86_64 or aarch64 (got $a)" ;; esac
done
[ -n "$DRIVER_VERSION" ] || die_usage "--driver-version is required"
case "$DRIVER_VERSION" in *[!0-9A-Za-z.+-]*|'') die_usage "--driver-version has unexpected characters" ;; esac
case "$MIN_RATIO" in
  0|1|0.[0-9]|0.[0-9][0-9]|0.[0-9][0-9][0-9]|1.0|1.00) ;;   # must also be valid JSON for jq --argjson (no leading dot)
  *) die_usage "--min-ratio must be a number between 0 and 1 written like 0.9" ;;
esac
case "$CONFIG_REPO" in */*) ;; *) die_usage "--config-repo must be owner/repo" ;; esac
case "$TIMEOUT" in ''|*[!0-9]*) die_usage "--timeout must be an integer" ;; esac
if [ -n "$WORKDIR" ]; then
  case "$WORKDIR" in /*) ;; *) die_usage "--workdir must be an absolute path" ;; esac
  mkdir -p "$WORKDIR"
else
  WORKDIR=$(mktemp -d)
fi
for tool in curl gh jq; do
  command -v "$tool" >/dev/null 2>&1 || { printf 'error: %s is required\n' "$tool" >&2; exit 2; }
done

N_BAD=0 N_ERR=0
printf 'START %s crawler-lists-gate driver-version=%s ref=%s/%s@%s min-ratio=%s workdir=%s\n' "$(date -u +%FT%TZ)" "$DRIVER_VERSION" "$CONFIG_REPO" "$CONFIG_PATH" "$CONFIG_REF" "$MIN_RATIO" "$WORKDIR"

DISTRO_FILTER_JSON=$(printf '%s\n' "${DISTROS[@]+"${DISTROS[@]}"}" | jq -R -s 'split("\n") | map(select(length > 0))')

for arch in "${ARCHES[@]}"; do
  list="$WORKDIR/list-$arch.json"
  hdr="$WORKDIR/list-$arch.hdr"
  url="$LISTS_BASE_URL/$arch/list.json"
  code=$(curl -sS -m "$TIMEOUT" -D "$hdr" -o "$list" -w '%{http_code}' "$url" 2>>"$WORKDIR/http-errors.log") || true
  if [ "${code:-000}" = "200" ] && jq -e 'type == "object"' "$list" >/dev/null 2>&1; then
    # last-modified value contains spaces: keep everything after the header name; awk never fails on a missing header
    lm=$(awk 'tolower($1) == "last-modified:" { sub(/^[^ ]+ /, ""); v = $0 } END { gsub(/\r/, "", v); printf "%s", v }' "$hdr")
    printf 'OK %s list %s last-modified=%s distros=%s\n' "$arch" "$url" "${lm:-unknown}" "$(jq -r 'keys | join(",")' "$list")"
  else
    printf 'ERROR %s list %s http=%s\n' "$arch" "$url" "${code:-000}"; N_ERR=$((N_ERR+1)); continue
  fi
  tree="$WORKDIR/tree-$arch.json"
  if ! gh api "repos/$CONFIG_REPO/git/trees/$CONFIG_REF:$CONFIG_PATH/$DRIVER_VERSION/$arch" > "$tree" 2>"$WORKDIR/tree-$arch.err"; then
    printf 'ERROR %s configs %s:%s/%s/%s trees API failed: %s\n' "$arch" "$CONFIG_REF" "$CONFIG_PATH" "$DRIVER_VERSION" "$arch" "$(head -c 200 "$WORKDIR/tree-$arch.err" | tr '\n' ' ')"
    N_ERR=$((N_ERR+1)); continue
  fi
  if [ "$(jq -r '.truncated' "$tree")" = "true" ]; then
    printf 'ERROR %s configs tree listing truncated by the API\n' "$arch"; N_ERR=$((N_ERR+1)); continue
  fi
  nconf=$(jq -r '[.tree[] | select(.type == "blob")] | length' "$tree")
  printf 'OK %s configs %s/%s/%s/%s files=%s\n' "$arch" "$CONFIG_REPO" "$CONFIG_PATH" "$DRIVER_VERSION" "$arch" "$nconf"

  # Fold config targets into list keys: exact key match first, then "<distro>-<flavour>" -> "<distro>".
  verdicts=$(jq -r --slurpfile cfg "$tree" --arg arch "$arch" --argjson ratio "$MIN_RATIO" --argjson only "$DISTRO_FILTER_JSON" '
    . as $list
    | [ $cfg[0].tree[] | select(.type == "blob") | .path | split("_")[0] ]
    | group_by(.) | map({t: .[0], n: length})
    | map(. as $it | . + {key: (if ($list | has($it.t)) then $it.t elif ($list | has($it.t | split("-")[0])) then ($it.t | split("-")[0]) else $it.t end)})
    | group_by(.key) | map({key: .[0].key, configs: (map(.n) | add), targets: (map(.t) | join(","))})
    | . as $groups
    | ($groups | map(.key)) as $with_configs
    | ($groups[] | .key as $key | select(($only | length) == 0 or (($only | index($key)) == null | not))
        | ($list[.key] // [] | length) as $ln
        | (if $ln == 0 then "MISSING" elif ($ln < (.configs * $ratio)) then "LOW" else "OK" end) as $v
        | "\($v) \($arch) \(.key) list=\($ln) configs=\(.configs) min=\((.configs * $ratio) | ceil) targets=\(.targets)"),
      ($list | keys[] | . as $key | select(($with_configs | index($key)) == null) | select(($only | length) == 0 or (($only | index($key)) == null | not))
        | "SKIP \($arch) \(.) list=\($list[.] | length) configs=0 (no configs for this distro in the reference directory)")
  ' "$list") || { printf 'ERROR %s evaluation failed (jq)\n' "$arch"; N_ERR=$((N_ERR+1)); continue; }
  printf '%s\n' "$verdicts"
  bad=$(printf '%s\n' "$verdicts" | grep -c -E '^(LOW|MISSING) ' || true)
  N_BAD=$((N_BAD + bad))
done

printf 'END %s blocking=%d errors=%d\n' "$(date -u +%FT%TZ)" "$N_BAD" "$N_ERR"
if [ "$N_ERR" -gt 0 ]; then printf 'CRAWLER_LISTS_BLOCK\n'; exit 4; fi
if [ "$N_BAD" -gt 0 ]; then printf 'CRAWLER_LISTS_BLOCK\n'; exit 1; fi
printf 'CRAWLER_LISTS_OK\n'
exit 0
